# Generated by Django 4.0.4 on 2022-07-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'leagues',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.IntegerField()),
                ('home', models.CharField(max_length=128)),
                ('away', models.CharField(max_length=128)),
                ('score', models.CharField(max_length=128)),
                ('time', models.DateTimeField()),
                ('league_id', models.IntegerField()),
            ],
            options={
                'db_table': 'matches',
            },
        ),
    ]
